config/routes.rb
Rails.application.routes.draw do
  root 'application#welcome'
  get 'signin' => 'sessions#new'
  get '/auth/facebook/callback' => 'sessions#create'
  post 'logout' => 'sessions#destroy'

  resources :users, only: [:show, :create, :new]
  resources :restaurants, only:[:new, :index, :create, :show, :edit, :update] do
    resources :experiences, only: [:new, :index, :show, :edit]
  end
  resources :sessions, only: :create
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user
  accepts_nested_attributes_for :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  validates :phone, format: { with: /\A\(?\d{3}\)?[- ]?\d{3}[- ]?\d{4}\z/,
                              message: "must be in the format (xxx) xxx-xxxx or xxx-xxx-xxxx"}
  validates :price, numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 10}
  has_many :experiences
  has_many :users, through: :experiences
  accepts_nested_attributes_for :experiences

  scope :denver, -> {where(city: "Denver")}
  scope :highest_price, -> {order('price desc').limit(5)}
  scope :lowest_price, -> {order('price asc').limit(5)}
  scope :most_frequented, -> {joins(:experiences).group('restaurant_id').order("count(experiences.restaurant_id) desc").limit(2)}
  def avg_rating
    if !self.experiences.empty?
      self.experiences.average(:rating).round(2)
    else
      "No ratings yet!"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, uniqueness: true
  validates :password_digest, presence: true
  has_secure_password
  has_many :experiences
  has_many :restaurants, through: :experiences
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def welcome

  end

  private

  def logged_in?
    !current_user.nil?
  end
  helper_method :logged_in?

  def current_user
    User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  def require_login
    redirect_to root_path unless session.include? :user_id
  end
  helper_method :require_login
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :require_login

  def new
    @restaurant = Restaurant.find_by(id: params[:restaurant_id])
    @experience = Experience.new(restaurant_id: @restaurant, user_id: current_user.id)
    if @restaurant.nil?
      redirect_to restaurants_path
    end
  end

  def edit
    @experience = Experience.find_by(id: params[:id])
    @restaurant = Restaurant.find_by(id: params[:restaurant_id])
    redirect_if_nil
  end

  def create
    @experience = Experience.create(experience_params)

    redirect_to restaurant_path(@experience.restaurant)
  end

  def update
    @experience = Experience.find_by(id: params[:id])
    redirect_if_nil

    @experience.update(experience_params)
    redirect_to restaurant_path(@experience.restaurant)
  end

  private

  def experience_params
    params.require(:experience).permit(:rating, :description, :user_id, :restaurant_id)
  end

  def redirect_if_nil
    if @experience.nil?
      redirect_to restaurant_path(params[:restaurant_id])
    end
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :require_login
  def new
    @restaurant = Restaurant.new
  end

  def show
    @restaurant = Restaurant.find_by(id: params[:id])
    redirect_if_nil
    respond_to do |format|
      format.html {render :index}
      format.json {render json: @restaurant, status: 200}
    end
  end

  def index
    @restaurants = Restaurant.all
    respond_to do |format|
      format.html {render :index}
      format.json {render json: @restaurants, status: 200}
    end

  end

  def edit
    @restaurant = Restaurant.find_by(id: params[:id])
    redirect_if_nil
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if (!@restaurant.save)
      serialized = RestaurantSerializer.new(@restaurant).as_json
      serialized["errors"] = @restaurant.errors.full_messages
      render json: serialized, status: 201
    else
      render json: @restaurant, status: 201
    end
  end

  def update
    @restaurant = Restaurant.find_by(id: params[:id])
    redirect_if_nil

    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :phone, :address, :city, :state, :price)
  end

  def redirect_if_nil
    if @restaurant.nil?
      redirect_to restaurants_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if params && params[:user]
      @user = User.find_by(id: params[:user][:id])
      if @user && @user.authenticate(params[:user][:password])
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      else
        flash[:message] = "Incorrect username or password!"
        redirect_to signin_path
      end
    elsif auth
      @user = User.find_or_create_by(name: auth['info']['name']) do |u|
        u.name = auth['info']['name']
        u.password = (0...8).map { (65 + rand(26)).chr }.join
      end
      session[:user_id] = @user.id
      @auth = auth
      redirect_to user_path(@user)
    else
      redirect_to signin_path
    end
  end

  def destroy
    session.delete(:user_id) if session[:user_id]
    redirect_to root_path
  end

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if params[:password] == params[:password_confirmation]
      @user = User.create(user_params)
      if @user.valid?
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      else
        render :new
      end
    else
      flash[:message] = "Passwords do not match!"
      redirect_to new_user_path
    end
  end

  def show
    @user = current_user
  end

=begin
  def edit
    @user = current_user
  end

  def update
    @user = User.find_by(id: params[:id])
    @user.update(user_params)
    if @user.valid?
      redirect_to user_path(@user)
    else
      render :edit
    end
  end
=end

  private

  def user_params
    params.require(:user).permit(:name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/welcome.html.erb
<h1>Welcome to your Restaurant Guide!</h1>
<% if logged_in? %>
  <h3><%= link_to "Create New Restaurant", new_restaurant_path %></h3>
  <h3><a id="all-restaurants" href="#">View All Restaurants</a></h3>
<% else %>
  <h3>Please login or create an account to continue!</h3>
<% end %>

<div id="restaurants">
  <a href="#" id="sort-all" hidden="true">Sort Restaurants</a>
</div>
<div id="show-restaurant">
  <h1 class="restaurantName"></h1>
  <p class="restaurantPhone"></p>
  <p class="restaurantAddress"></p>
  <p class="restaurantPrice"></p>

  <div id="experiences">
  </div>
</div>

app/views/experiences/_form.html.erb
<%= form_for e do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :restaurant_id, value: r.id %>
  <%= f.label :rating %><br>
  <%= f.number_field :rating, in: 1.0..10.0, step: 0.1 %><br>
  <%= f.label :description %><br>
  <%= f.text_field :description %><br>
  <%= f.submit button_text %>
<% end %>

app/views/experiences/edit.html.erb
<div class="center info">
  <h1>Edit Review</h1>
  <%= render partial: 'form', locals: {e: @experience, r: @restaurant, button_text: "Update Review"} %>
</div>

app/views/experiences/new.html.erb
<div class="center info">
<h1>Write a Review</h1>
  <%= render partial: 'form', locals: {e: @experience, r: @restaurant, button_text: "Submit Review"} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantGuide</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_url %>"/>Home</a>
        <% if logged_in? %>
          <%= link_to "#{current_user.name}'s profile", user_path(current_user), :class => "navbar-brand" %>
          <%= link_to "Log Out", logout_path, method: :post, :class => "navbar-brand" %>
        <% else %>
          <a class="navbar-brand" href="<%= new_user_path %>">Sign Up</a>
          <a class="navbar-brand" href="<%= signin_path %>">Log In</a>
        <% end %>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">

        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>

  <!-- content -->
  <div class="container"  role="main">
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>
    </div>

    <%= yield %>
  </div>

  <script type="text/javascript" charset="utf-8">
    $(document).on("turbolinks:load", addEventListeners());
  </script>
  </body>
</html>

app/views/restaurants/_display.html.erb
<div class="center info">
  <% if display_name %>
    <h3><%= r.name %><br></h3>
  <% end %>
  <strong>Phone: </strong><%= r.phone %><br>
  <strong>Address: </strong><%= r.address %><br>
  <strong>City: </strong><%= r.city %><br>
  <strong>State: </strong><%= r.state %><br>
  <strong>Price (1-10): </strong><%= r.price %><br>
  <strong>Average Rating (1-10): </strong><%= r.avg_rating %><br>

  <%= link_to "Edit Restaurant", edit_restaurant_path(r) %><br>
  <%= link_to "Write a Review", new_restaurant_experience_path(r)  %><br>
  <%= link_to "View Restaurant", restaurant_path(r) %>
</div>

app/views/restaurants/_form.html.erb
<% if r.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(r.errors.count, "error") %>
      prohibited this restaurant from being saved:
    </h2>

    <ul>
      <% r.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_for r do |f| %>
  <div class="field<%= " field_with_errors" if r.errors[:name].any?%>">
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
  </div>
  <div class="field<%= " field_with_errors" if r.errors[:phone].any?%>">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %><br>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %><br>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %><br>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %><br>
  </div>
  <div class="field<%= " field_with_errors" if r.errors[:price].any?%>">
    <%= f.label :price %><br>
    <%= f.text_field :price %><br>
  </div>

  <%= f.submit button_text %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>
<%= render partial: 'form', locals: {r: @restaurant, button_text: "Update Restaurant"} %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<% Restaurant.all.each do |r| %>
  <%= render partial: 'display', locals: {r: r, display_name: true}%>
  <br>
<% end %>

<%= link_to "Create Restaurant", new_restaurant_path %>

app/views/restaurants/most_frequented.html.erb
<h1>Most Frequented</h1>
<% Restaurant.most_frequented.each do |r| %>
  <%= render partial: "display", locals: {r: r, display_name: true} %>
  <br>
<% end %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>
<div>
  <ul class="errors">

  </ul>
</div>
<%= render partial: 'form', locals: {r: @restaurant, button_text: "Create Restaurant"}, class: "new_restaurant_form" %>

<div class="restaurantInfo">
  <h1 class="restaurantName"></h1>
  <p class="restaurantPhone"></p>
  <p class="restaurantAddress"></p>
  <p class="restaurantPrice"></p>
  <a href="/restaurants/new" class="newRestaurant" hidden="true">Create Another Restaurant</a>
</div>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<%= render partial: 'display', locals: {r: @restaurant, display_name: false} %>
<h1>Reviews</h1>
<% @restaurant.experiences.each do |experience| %>
  <div class="center review">
    <strong>User: </strong><%=experience.user.name %><br>
    <strong>Rating: </strong><%=experience.rating %><br>
    <strong>Description: </strong><%=experience.description %><br>
    <% if experience.user == current_user %>
      <%= link_to "Edit Review", edit_restaurant_experience_path(@restaurant, experience) %>
    <% end %>
  </div>
  <br>
<% end %>

app/views/users/new.html.erb
<h1>Create User</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this user from being saved:
    </h2>

    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for User.new do |f| %>
  <div class="field<%= " field_with_errors" if @user.errors[:name].any?%>">
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
  </div>
  <%= f.label :password %><br>
  <%= f.password_field :password %><br>
  <%= f.label :password_confirmation, "Confirm Password" %><br>
  <%= f.password_field :password_confirmation %><br>
  <%= f.submit "Create User" %>
<% end %>

app/views/users/show.html.erb
<div class="center info">
  <h2>My Profile</h2>
  <strong>Name: </strong><%= @user.name %>
  <br>
  <%= link_to "View Restaurants", restaurants_path %>
</div>
<br>
<% if !@user.restaurants.empty? %>
  <h2>Your Restaurants</h2>
  <% @user.restaurants.uniq.each do |r| %>
    <%= render partial: 'restaurants/display', locals: {r: r, display_name: true} %>
  <% end %>
<% end %>